// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARzRpkwUoc0wb6dnKV2N_BqAfYwlNz5_8',
    appId: '1:902170768437:web:8161790542b99012552d7c',
    messagingSenderId: '902170768437',
    projectId: 'em-app-f687f',
    authDomain: 'em-app-f687f.firebaseapp.com',
    storageBucket: 'em-app-f687f.firebasestorage.app',
    measurementId: 'G-JWGM5VCL0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXSgDl8yu3-vh6-tyth6vzsF1v5Ru_TI',
    appId: '1:902170768437:android:2dfa52e9f1c87f73552d7c',
    messagingSenderId: '902170768437',
    projectId: 'em-app-f687f',
    storageBucket: 'em-app-f687f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYCzu4njUwUuwvlo9eo4xtAUakOpBMVQ',
    appId: '1:902170768437:ios:428875036c902301552d7c',
    messagingSenderId: '902170768437',
    projectId: 'em-app-f687f',
    storageBucket: 'em-app-f687f.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYCzu4njUwUuwvlo9eo4xtAUakOpBMVQ',
    appId: '1:902170768437:ios:428875036c902301552d7c',
    messagingSenderId: '902170768437',
    projectId: 'em-app-f687f',
    storageBucket: 'em-app-f687f.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARzRpkwUoc0wb6dnKV2N_BqAfYwlNz5_8',
    appId: '1:902170768437:web:751beed166e78f9a552d7c',
    messagingSenderId: '902170768437',
    projectId: 'em-app-f687f',
    authDomain: 'em-app-f687f.firebaseapp.com',
    storageBucket: 'em-app-f687f.firebasestorage.app',
    measurementId: 'G-Y036WC2K1Z',
  );
}
